(function(_ds){var window=this;var msa=function(){return(0,_ds.T)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},nsa=function(){return(0,_ds.T)('<div class="devsite-book-nav-blur"></div>')},osa=function(a){a=a.eL;a=_ds.eP(new _ds.cP("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.U(_ds.ds(1)),XXX_2:_ds.U(_ds.ds(a))});return(0,_ds.T)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var psa="onpointerover"in window?"pointerover":"mouseover",y2=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Hj(a,"visually-hidden","",c))},qsa=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:
0;_ds.Jn(a.eventHandler,a,_ds.Yh,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.j.removeAttribute("animatable")});_ds.Hj(a,"animatable","");b=_ds.Se(a.m`animatable`);b(a.background,"animatable","");b(a.j,"animatable","");a.hasAttribute("collapsed")?(_ds.Hj(a,"aria-label","Hide side navigation",a.Oc),_ds.Hj(a,"data-title","Hide side navigation",a.Oc),a.removeAttribute("collapsed"),_ds.HJ(a.Oc,"expanded","true"),z2(a,"Expanded book nav")):(_ds.Hj(a,"aria-label","Show side navigation",
a.Oc),_ds.Hj(a,"data-title","Show side navigation",a.Oc),_ds.Hj(a,"collapsed",""),_ds.HJ(a.Oc,"expanded","false"),z2(a,"Collapsed book nav"),_ds.Jn(a.eventHandler,a,_ds.Yh,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.um();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},ssa=function(a){a.eventHandler.listen(a,"click",b=>void A2(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&A2(a,b)});a.eventHandler.listen(a,
[psa,"focusin"],b=>void rsa(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.h&&(B2(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Hj(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.ya.fb());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.ya.fb()});a.eventHandler.listen(a,"scroll",()=>{_ds.Hj(a,"user-scrolled","")});a.eventHandler.listen(a.Oc,"click",()=>{a.Ea.fb()});a.g&&(a.eventHandler.listen(a.g,"keyup",()=>void a.Da.fb()),
a.eventHandler.listen(a.g,"focus",()=>void a.xa("focus")));a.ea&&a.eventHandler.listen(a.ea,["click","keydown"],b=>{if("click"===b.type||13===b.keyCode||27===b.keyCode){a.g&&(a.g.value="",a.g.focus());let c;null==(c=a.ea)||c.classList.add("hidden");C2(a);D2(a);a.xa(b.type)}})},E2=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.v=new Set(b);if(!_ds.D().hash&&c)tsa(a,a.v);else{c=new _ds.oP;for(const d of a.v)_ds.nP(c,d)}},F2=async function(a){const b=await _ds.t();for(const c of a.v)b.unregisterIntersectionForElement(c)},
A2=function(a,b){if(!b.defaultPrevented){var c=b.target;"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Hj(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&B2(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.Hj(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.h&&(d=a.h.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},rsa=function(a,b){b.defaultPrevented||(b=_ds.ml(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Ee(b,_ds.ye(_ds.mm(b.href).href)))},G2=function(a){a.ra=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},
I2=function(a){const b=_ds.D().searchParams.get("nf");a.g&&b&&(a.g.value=b,H2(a))},H2=function(a){if(a.ra.length){C2(a);D2(a);var b,c,d=null==(b=a.g)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.ea)||e.classList.remove("hidden");for(const g of a.ra){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=
e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.Qe(f,_ds.mf(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&
(a=_ds.N(osa,{eL:a}),b.appendChild(a))}}else null==(f=a.ea)||f.classList.add("hidden")}},C2=function(a){for(const b of a.ra){let c;b.classList.toggle("hidden",!(null==(c=a.g)||!c.value))}},D2=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.Qe(a,_ds.mf(b))}}},
tsa=async function(a,b){if(a.connected){var c=await _ds.t(),d=new _ds.oP,e=f=>{f=f.target;_ds.nP(d,f);a.v.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},B2=function(a,b){let c=!1;if(a.h)for(const d of a.h.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.Hj(a,"hidden","",d);return c},J2=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");
a=_ds.Bm(_ds.D().pathname);a=`[href="${_ds.mm(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},K2=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},usa=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.um(),await L2(a),await a.Fa,await _ds.t(),await _ds.um(),
await L2(a))},L2=async function(a){if(a.connected&&a.h){await _ds.t();var b=a.h.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await vsa(a,b))}},vsa=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Zn(b,a,!0).y;await _ds.um();c&&_ds.Hj(a,"user-scrolled","")}},z2=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},M2=class extends _ds.C{static get observedAttributes(){return["collapsed",
"fixed","hidden"]}constructor(){super();this.connected=!1;this.ea=this.g=this.oa=this.h=null;this.ra=[];this.eventHandler=new _ds.F;this.Ba=()=>{};this.v=new Set;_ds.Gj(this,this.m`animatable`,this.m`aria-expanded`,this.m`aria-label`,this.m`collapsed`,this.m`data-title`,this.m`fixed`,this.m`has-book-nav`,this.m`hidden`,this.m`top-level-nav`,this.m`user-scrolled`,this.m`visually-hidden`);this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.Oc=_ds.N(msa);
this.j=_ds.N(nsa);this.Fa=new Promise(a=>{this.Ba=a});this.ya=new _ds.Gn(()=>{this.connected&&y2(this)},20);this.Da=new _ds.Gn(()=>{H2(this)},20);this.Ea=new _ds.Gn(()=>{qsa(this)},100)}async connectedCallback(){this.connected=!0;_ds.Qk(this.background,this);this.hasAttribute("hidden")&&(_ds.Hj(this,"hidden","",this.Oc),_ds.Hj(this,"hidden","",this.j));let a;null==(a=this.parentElement)||a.insertBefore(this.Oc,this.nextSibling);_ds.Hj(this,"aria-label","Hide side navigation",this.Oc);_ds.Hj(this,
"data-title","Hide side navigation",this.Oc);_ds.Hj(this,"aria-expanded","true",this.Oc);let b;null==(b=this.parentElement)||b.insertBefore(this.j,this.nextSibling);if(this.oa=this.querySelector(".devsite-book-nav-filter"))this.g=this.oa.querySelector("input[type=text]"),this.ea=this.oa.querySelector(".filter-clear-button"),G2(this),I2(this);y2(this);ssa(this);await this.init();E2(this)}disconnectedCallback(){this.connected=!1;_ds.H(this.eventHandler);F2(this);this.v.clear();var a=document.querySelector("#devsite-hamburger-menu");
a&&_ds.Hj(this,"visually-hidden","",a);a=[this.background,this.Oc,this.j];for(const b of a)b&&_ds.Sk(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.j.removeAttribute("animatable");this.j.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=
document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Hj(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.Oc,this.j];for(const d of c)d&&(b?_ds.Hj(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.Ba()}async init(a=!0){if(this.connected){this.j.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);
this.h=this.querySelector(".devsite-mobile-nav-bottom");_ds.Hj(this,"top-level-nav","");this.h&&this.h.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.Hj(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.Hj(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(J2(this),K2(this),await usa(this)):(await _ds.um(),await L2(this))}}async Ac(a){a?(a=a.querySelector("nav")||null,J2(this,a),
K2(this,a),a&&(await F2(this),this.v.clear(),E2(this,a,!1)),_ds.Jj(this,this.querySelector("nav"),a)):_ds.Pk(this);G2(this);if(this.g){this.g.value="";let b;null==(b=this.ea)||b.classList.add("hidden");I2(this)}await _ds.um();await this.init(!1)}xa(a){this.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:a,label:"focus"===a?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))}};
M2.prototype.updateContent=M2.prototype.Ac;M2.prototype.attributeChangedCallback=M2.prototype.attributeChangedCallback;M2.prototype.disconnectedCallback=M2.prototype.disconnectedCallback;M2.prototype.connectedCallback=M2.prototype.connectedCallback;var wsa=class extends M2{async xa(a){super.xa(a);a={eventData:JSON.stringify({type:"devsite-nav-filter",name:"focus"===a?"inputEntered":"filterCleared"})};this.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:a,bubbles:!0}))}};try{customElements.define("devsite-book-nav",wsa)}catch(a){console.warn("Unrecognized DevSite custom element - CloudBookNav",a)};})(_ds_www);
