(function(_ds){var window=this;var X3=function(a){return!a.classList.contains("material-icons")},oua=async function(a,b){var c=await _ds.t();const d=_ds.D();c=c.getInsecureHost();b=b.Ha;var e=b.origin===d.origin;if(c){if(b.origin!==c&&!e)return}else if(!e)return;let f;try{f=(0,_ds.Po)(b.data)}catch(g){return}c=_ds.Fh(f,1,0);if(4===c)await gua(a,b);else if(e=f.getName())if(e=a.querySelector(`devsite-iframe iframe[name="${e}"]`))switch(c){case 5:await hua(b,f,e);break;case 8:await iua(b,f,d);break;case 1:await jua(b,f,d);break;case 6:case 7:await kua(c,
d,f);break;case 9:await lua(a,f);break;case 10:await mua(f,d);break;case 13:await nua(f)}},Y3=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.remove("hidden")})},pua=async function(a,b){if(b.detail){var c=b.detail.bottomPanelHeight,d=b.detail.contentHeight,e=b.detail.contentMargin,f=b.detail.offset,g=b.detail.panelCoversContent,h=b.detail.x;b=b.detail.y;var k=new _ds.Ko;c=_ds.Lh(k,8,c);d=_ds.Lh(c,6,d);e=_ds.Lh(d,7,e);f=_ds.Lh(e,5,f);g=_ds.Kh(f,9,g);h=_ds.Lh(g,
1,h);h=_ds.Lh(h,2,b);h=_ds.Lh(_ds.Lh(h,3,_ds.Hk().height),4,_ds.Hk().width);b=_ds.Mo(13);h=_ds.sh(b,13,h);for(const l of a.iframes)l&&l.contentWindow&&Z3(l.contentWindow,h)}},$3=function(a){qua(a);a.j=a.querySelector(".devsite-article-body");a.j&&(rua(a),a.iframes=[]);a.g&&a.g.disconnect();a.h.clear();sua(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");var d=void 0;const e=null==(d=b)?void 0:
d.querySelectorAll("source:not(.devsite-dark-theme)");let f;const g=null==(f=b)?void 0:f.querySelector("img");let h;(null==(h=e)?0:h.length)?c.remove():b&&g&&b.replaceWith(g)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));"docs"===document.body.getAttribute("layout")&&a.j&&(d=Array.from(a.j.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...d));a.h.clear();a.h=new Set(c);if(_ds.D().hash){c=new _ds.oP;for(const e of a.h)_ds.nP(c,e,X3)}else tua(a,
a.h);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},sua=function(a){Array.from(a.querySelectorAll("*:not(.devsite-table-wrapper) > table")).forEach(b=>{const c=document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Qk(c,b);c.appendChild(b)})},qua=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.add("hidden")})},
gua=async function(a,b){if(b.source){var c=uua(a,b.source);if(c){const e=_ds.vk();c.setAttribute("name",e);var d=_ds.Mo(3);d=_ds.y(d,2,e);Z3(b.source,d);(b=document.body.getAttribute("appearance"))&&a4(c,b);a.iframes.push(c)}}},hua=async function(a,b,c){await _ds.Bf();var d=_ds.Jk(document).y,e=b.Qe();const f=_ds.Ch(b,3);a:{var g;if(_ds.Pj&&(g=c.parentElement)){c=g;break a}g=c.parentNode;c=_ds.Zk(g)?g:null}e&&(null==c||c.setAttribute("width",`${e}px`));f&&(null==c||c.setAttribute("height",`${f}px`));
window.scrollTo({left:_ds.Jk(document).x,top:d});_ds.Cf();d=new _ds.Ko;d=_ds.Lh(d,1,window.scrollX);d=_ds.Lh(_ds.Lh(_ds.Lh(d,2,window.scrollY),3,_ds.Hk().height),4,_ds.Hk().width);e=_ds.Mo(5);d=_ds.sh(e,13,d);b=_ds.No(d,_ds.x(b,8));Z3(a.source,b)},iua=async function(a,b,c){a.source&&(b=_ds.No(_ds.Mo(8),_ds.x(b,8)),c=_ds.y(b,6,c.toString()),Z3(a.source,c))},jua=async function(a,b,c){a.source&&(b=_ds.No(_ds.Mo(2),_ds.x(b,8)),c=_ds.y(b,7,`${c.search}${c.hash}`),Z3(a.source,c))},kua=async function(a,
b,c){const d=c.getTitle();c=new URL(c.getUrl(),b.origin);b.search=c.search;b.hash=c.hash;b=b.href.replace(b.origin,"");6===a?_ds.hm(b,!1,!0,void 0,void 0,d):_ds.hm(b,!0,!0,void 0,void 0,d)},lua=async function(a,b){const c=_ds.x(b,9);let d;try{d=JSON.parse(_ds.x(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",
{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}))},mua=async function(a,b){a=a.getUrl();const c=await _ds.t();if(a){const d=new URL(a,b.origin);a.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?await c.scrollToAnchor(d.hash,!0):await c.fetchPage(d.href)}},nua=async function(a){var b;const c=(null==(b=_ds.Oo(a))?void 0:_ds.Ch(b,1))||0;let d;b=(null==(d=_ds.Oo(a))?void 0:_ds.Ch(d,
2))||0;let e;window.scrollTo({left:c,top:b,behavior:(null==(e=_ds.Oo(a))?0:_ds.Bh(e,10))?"smooth":"auto"})},Z3=function(a,b){a&&a.postMessage(b.Hb(),"*")},uua=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.al(d)===b&&(c=d)});return c},a4=function(a,b){var c=_ds.Mo(12);b=_ds.y(c,12,b);a&&a.contentWindow&&Z3(a.contentWindow,b)},rua=function(a){if("full"===document.body.getAttribute("layout")){let b;(a=null==(b=a.j)?void 0:b.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(c=>{c.removeAttribute("tabindex")})}},tua=function(a,b){a.g&&b.forEach(c=>{let d;null==(d=a.g)||d.observe(c)})},b4=class extends _ds.C{constructor(){super();this.eventHandler=new _ds.F;this.v=new _ds.F;this.h=new Set;this.j=null;this.iframes=[];this.g=null;"IntersectionObserver"in window&&(this.g=new IntersectionObserver(a=>{for(const b of a)if(b.isIntersecting){a=b.target;_ds.nP(new _ds.oP,a,X3);this.h.delete(a);let c;null==(c=this.g)||c.unobserve(a)}},{rootMargin:"100%"}))}connectedCallback(){this.eventHandler.listen(window,
"message",a=>{oua(this,a)});this.eventHandler.listen(document.body,"devsite-appearance-updated",a=>{if(a=a.Ha.detail.preference)for(const b of this.iframes)a4(b,a)});this.eventHandler.listen(document.body,"devsite-page-loaded",()=>{Y3(this)});this.eventHandler.listen(document.body,"devsite-sticky-scroll",a=>{pua(this,a.Ha)});$3(this)}disconnectedCallback(){this.g&&this.g.disconnect();this.h.clear();_ds.H(this.eventHandler);_ds.H(this.v)}Ac(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer",
"devsite-notification"].forEach(b=>{_ds.Jj(this,this.querySelector(b),a.querySelector(b))}),$3(this),Y3(this))}};b4.prototype.updateContent=b4.prototype.Ac;b4.prototype.disconnectedCallback=b4.prototype.disconnectedCallback;b4.prototype.connectedCallback=b4.prototype.connectedCallback;try{customElements.define("devsite-content",b4)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
